<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qD4jvXa' shared service.

return $this->privates['.service_locator.qD4jvXa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tr' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
], [
    'tr' => 'App\\Repository\\TransactionRepository',
]);
