<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.U.DKYVZ' shared service.

return $this->privates['.service_locator.U.DKYVZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'account' => ['privates', '.errored..service_locator.U.DKYVZ.App\\Entity\\Account', NULL, 'Cannot autowire service ".service_locator.U.DKYVZ": it references class "App\\Entity\\Account" but no such service exists.'],
    'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
], [
    'account' => 'App\\Entity\\Account',
    'transactionRepository' => 'App\\Repository\\TransactionRepository',
]);
