<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iQVB366' shared service.

return $this->privates['.service_locator.iQVB366'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'carteBancaireRepository' => ['privates', 'App\\Repository\\CarteBancaireRepository', 'getCarteBancaireRepositoryService.php', true],
], [
    'carteBancaireRepository' => 'App\\Repository\\CarteBancaireRepository',
]);
