<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KZGsgyH' shared service.

return $this->privates['.service_locator.KZGsgyH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'accountRepository' => ['privates', 'App\\Repository\\AccountRepository', 'getAccountRepositoryService.php', true],
], [
    'accountRepository' => 'App\\Repository\\AccountRepository',
]);
