<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\TransactionService' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/TransactionService.php';

return $this->privates['App\\Service\\TransactionService'] = new \App\Service\TransactionService();
