<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wc24vR1' shared service.

return $this->privates['.service_locator.wc24vR1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'person' => ['privates', '.errored..service_locator.wc24vR1.App\\Entity\\Person', NULL, 'Cannot autowire service ".service_locator.wc24vR1": it references class "App\\Entity\\Person" but no such service exists.'],
], [
    'person' => 'App\\Entity\\Person',
]);
