<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._.cEM4j' shared service.

return $this->privates['.service_locator._.cEM4j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'carteBancaire' => ['privates', '.errored..service_locator._.cEM4j.App\\Entity\\CarteBancaire', NULL, 'Cannot autowire service ".service_locator._.cEM4j": it references class "App\\Entity\\CarteBancaire" but no such service exists.'],
], [
    'carteBancaire' => 'App\\Entity\\CarteBancaire',
]);
