<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.U.DKYVZ.App\Entity\Account' shared service.

include_once $this->targetDirs[3].'/src/Entity/Account.php';

return $this->privates['.errored..service_locator.U.DKYVZ.App\\Entity\\Account'] = new \App\Entity\Account();
