<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKVDCLVC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKVDCLVC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKVDCLVC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKVDCLVC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKVDCLVC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KVDCLVC',
    'container.build_id' => '6a805491',
    'container.build_time' => 1574349703,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKVDCLVC');
